### ISSUE TITLE
SWATH

### ISSUE THREAD

**Issue by VeryGenome** [GarrettLab-UF/LipidMatch#1]
Excuse me,can LipidMatch process data acquired from data independent acquisition (DIA) ,for example ,SWATH mode in an SCIEX 5600 machine?Thank you!

**Comment by jeremykoelmel** [comment]
We do have users who use the SCIEX 5600, although with iterative exclusion (IE) and DDA data. LipidMatch does not support SWATH (the only DIA approach it supports is AIF for thermo vendors). 

One of our users uses SWATH and analyzes the data with MS-DIAL and IE-DDA and analyzes the data with LipidMatch:

"Combining dataset for each polarity using IE for DDA and MS-Dial for SWATH resulted in “identifying” a large number of lipids biomarkers in my untargeted approach...
LipidMatch is definitely part of our lipidomics platform analysis now."

**Comment by VeryGenome** [comment]
Jeremy,thank you so much for your reply and advice.Our lab focus on the plant sphingolipid but I haven't got the experience for processing SWATH data before.I have read the manual of MS-DIAL and analysed the example data,that was OK,but when I try to analyse my data,I find that was so difficult for me to adjust the parameters,can you share some experience for analyzing the SWATH data in MS-DIAL?Appreciate for your help!Richard Liu

**Comment by jeremykoelmel** [comment]
Hiroshi may be able to help you (MS-DIAL developer):
hiroshi.tsugawa@riken.jp

**Comment by VeryGenome** [comment]
Thanks again for your help!

**Comment by JasonCochran** [comment]
If you have any more questions you can open a new issue or email us!
Thanks,
Jason
