### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by xiaodfeng** [GarrettLab-UF/LipidMatch#2]
When I am running lipidMatch using the example dataset and the example library. There come across the following problem:

> Error in file(file, "rt") : cannot open the connection

Is there some way to fix it ?

Thank you.

**Comment by carlospenno** [comment]
Hi, 

I have had the same issue and found that a library file is missing and causing this error. 
The library file missing is the TG_reduced_NH4.csv 

I have already contacted the authors but got not a answer from them.

Best, Carlos.

**Comment by jeremykoelmel** [comment]
Please see new libraries attached. We will also upload and change those libraries in the master. There were actually a number of libraries missing, there may have been an incomplete transfer somewhere along the line. I appreciate you finding the issue and reporting the issue, let me know if I can be of anymore help. 
[LipidMatch_Libraries.zip](https://github.com/GarrettLab-UF/LipidMatch/files/2229571/LipidMatch_Libraries.zip)

**Comment by jeremykoelmel** [comment]
You can use these libraries, also if you are using LipidMatch Flow you can replace the libraries (make sure they are unzipped and in the exact same file location).

**Comment by JasonCochran** [comment]
We have an official release to fix this problem. It is linked above below. If the problem persists please let us know and we will continue investigating. If you have different errors you can open another issue for us to address them. Thanks!

https://github.com/GarrettLab-UF/LipidMatch/releases/tag/V2.0.1

**Comment by xiaodfeng** [comment]
Thank you for the update of LipidMatch libraries. I have tested these two libraries using the example data-set. And I find that the LipidMatch V2.0.1 still have the same problem. But if I use the libraries uploaded by jeremykoelmel, it works fine. By the way, I have also tried running  LipidMatch on R 3.5.0, but it failed. Is it possible to let LipidMatch support  R 3.5.0?

**Comment by JasonCochran** [comment]
v2.0.2 of LipidMatch should contain the fixes to the missing library error. 
Currently, LipidMatch supports R v3.3.3 as the latest version contains incompatible features that will break the software. In the future, we will consider porting the software to run on a more recent R distribution. Is there a particular reason you would like R v3.5.0?

**Comment by fxd1106** [comment]
Dear Jason,

    Thank you for the quick update of the LipidMatch library. v2.0.2 of LipidMatch is OK now. I am currently using R v3.5.0, so I need to transfer into R v3.3.3 if I want to use LipidMatch. But it's also fine to use R v3.3.3. May I have the raw data of 2016_3_11_RC_Plasma.csv? As I also want to perform the feature detection using XCMS and Progenesis.

Best regards,
Xiaodong

**Comment by fxd1106** [comment]
Dear Jason,

    Thank you for the quick update of the LipidMatch library. v2.0.2 of LipidMatch is OK now. I am currently using R v3.5.0, so I need to transfer into R v3.3.3 if I want to use LipidMatch. But it's also fine to use R v3.3.3. May I have the raw data of 2016_3_11_RC_Plasma.csv? As I also want to perform the feature detection using XCMS and Progenesis.

Best regards,
Xiaodong

**Comment by xiaodfeng** [comment]
Dear Jason,

Thank you for the quick update of the LipidMatch library. v2.0.2 of LipidMatch is OK now. I am currently using R v3.5.0, so I need to transfer into R v3.3.3 if I want to use LipidMatch. But it's also fine to use R v3.3.3. May I have the raw data of 2016_3_11_RC_Plasma.csv? As I also want to perform the feature detection using XCMS and Progenesis.

Best regards,
Xiaodong

**Comment by jeremykoelmel** [comment]
Hello Xiadong,
You can have two working versions of R on a single computer, without any problem. Hopefully that will work for you. We will not change the dependency on R version 3.3.3 because R has and will change, and hence we rather stick with a R version we know LipidMatch will work with. 

As for the .raw files, there are 22 of them which is a few GB, which I imagine I cannot upload to Github. These types of comparisons are very useful, especially with feature detection where there is no perfect solution. I might have a smaller set that would be better to employ, and I can give you the feature table I generate using LipidMatch Flow (MZmine) for comparison. Would you prefer Agilent or Thermo files? Note that each have very different parameters. 

You can email me at jeremykoelmel@gmail.com and I will send you the files.

**Comment by xiaodfeng** [comment]
Dear Jeremy,

Thank you for your reply. I have already installed 2 version of R in the Linux system. An email has been sent for the .raw data.

Best regards,
Xiaodong

**Comment by JasonCochran** [comment]
Please reopen another issue if you have questions or concerns regarding our software.
Thanks,
Jason
