### ISSUE TITLE
Error in RunTargeted(MS2_df_in, FeatureList_in, LibraryFile, ParentMZcol_in,  :    could not find function "sqldf"

### ISSUE THREAD

**Issue by stolltho** [GarrettLab-UF/LipidMatch#5]
The code always throws an error when it comes to reading the MS2 files.
Any idea what the issue is?
Cheers,
Thomas
R vers 3.3.3

Reading in file:	area_featureTable01_pos.csv
From Directory:		C:/R_WorkingDirectory/Sputum_OxLipids/Input/area_featureTable01_pos.csv
Reading in file:	CE20_01_ddMS2_pos.ms2
From Directory:		C:/R_WorkingDirectory/Sputum_OxLipids/Input/CE20_01_ddMS2_pos.ms2
Read 3872753 items
**Error in RunTargeted(MS2_df_in, FeatureList_in, LibraryFile, ParentMZcol_in,  : 
  could not find function "sqldf"**
> 
> options(warn=0)#suppress warning off
> 
> Rversion<-(paste("ERROR:R version must be equal to, or between, 2.0.3 and 3.3.3. Please download 3.3.3. You are using version: ", paste(version$major,version$minor,sep=".")))
> OutputRemoval<-paste("ERROR: Remove your 'Output' folder from the current Input Directory: ", InputDirectory)
> 
> 
> #DEBUG CreateIDs
> # ddMS2directory<-"Nothing"
> # Classdirectory<-"Nothing"
> # AIFdirectory<-paste(OutputDirectoryAIFPos_in,"Confirmed_Lipids\\", sep="")
> # PeakTableDirectory <- paste(fpath,FeatureTable_POS,sep="")
> # ddMS2directory <- ddMS2directory
> # Classdirectory <- Classdirectory
> # AIFdirectory <- AIFdirectory
> # ImportLib <- ImportLibPOS
> # OutputDirectory <- OutputDirectory
> # ddMS2 <- PosDDLib
> # ddMS2Class <- PosClassDDLib
> # AIF <- PosAIFLib
> # mode <- "Pos"
> 
> #CreateIDs(paste(fpath,FeatureTable_POS,sep=""), ddMS2directory, Classdirectory, 
> #AIFdirectory, ImportLibPOS, OutputDirectory, PosDDLib, PosClassDDLib, PosAIFLib, "Pos")
> 
> #Debug AIF
> # ms1_df<-MS1_df_in
> # ms2_df<-MS2_df_in
> # FeatureList<-FeatureList_in
> # LibraryLipid_self<-LibraryFile
> # ParentMZcol<-ParentMZcol_in
> # OutputDirectory<-OutputDirectoryAIFNeg_in
> # ExtraFileNameInfo<-OutputName
> # ConfirmORcol<-ConfirmORCol
> # ConfirmANDcol<-ConfirmANDCol
> 
> if(!((as.numeric(paste(version$major,version$minor,sep=""))>=20.3) && (as.numeric(paste(version$major,version$minor,sep=""))<=33.3))) {
+   Rversion
+ }
> 
> if(ErrorOutput==1){
+   OutputRemoval
+ }
>

**Comment by jeremykoelmel** [comment]
Based on your error, it seems it is not installing SQLDF correctly, are you connected to the internet?
If so try:
install.packages("sqldf",  repos = c(CRAN = "http://cran.rstudio.com"))
library(sqldf)

and makes sure sqldf installs and loads properly. You can try ?sqldf() and help should show up if it is installed correctly after loading. 

If not you can send the .ms2 file and feature table to me jeremykoelmel@gmail.com and if I have time I can check what is happening.

**Comment by jeremykoelmel** [comment]
People are having errors as "blob" is not installing correctly.
Try:
> install.packages("RSQLite")
Installing package into ‘C:/Users/COMPUTER/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ellipsis’, ‘rlang’, ‘vctrs’, ‘blob’

 There are binary versions available but the source versions are later:
        binary source needs_compilation
rlang    0.2.0  0.4.0              TRUE
blob     1.1.1  1.2.0             FALSE
RSQLite  2.1.0  2.1.2              TRUE

Do you want to install from sources the packages which need compilation?
y/n: y
Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘ellipsis’ ‘vctrs’
Do you want to attempt to install these from sources?
y/n: n

Let me know if that works, as I cannot recreate the problem (packages and code work fine for me and all computers I am using on)

**Comment by jeremykoelmel** [comment]
Oops for:
Do you want to install from sources the packages which need compilation?
y/n: 
PUT "n"

**Comment by jeremykoelmel** [comment]
From Sara (Another LipidMatch User), who had a similar issue:
"I've resolve the issue downloading the LipidMatch flow file and using the R version that is already there."
DL LipidMatch Flow here:
http://secim.ufl.edu/secim-tools/lipidmatchflow/
Find R in the following directory:
...LipidMatch_Flow-0.0.2\LipidMatch_Flow\R-3.3.3\bin

Copy and paste script and see if that solves the issue

**Comment by MPN-chemistry** [comment]
What about provide a list of all the packages required to run LipidMatch (not Flow)?  Moreover, what about providing the script to install all of the required packages so that a user may simply copy and paste the text into their console, if that's even possible?

**Comment by ijmiller2** [comment]
For future reference, I was not able to install the "blob" package with R 3.3.3, but the examples in the tutorial do appear to work if you use R provided in `LipidMatch_Flow-0.0.2\LipidMatch_Flow\R-3.3.3\bin` as suggested above.

**Comment by jeremykoelmel** [comment]
Also version 3.0.0 should now work: Please see the tutorial for applying the R Packages which are included with the release. Therefore you do not need to download any R packages but use the ones included. Let me know if there are any bugs in this new version.
