### ISSUE TITLE
output folder empty

### ISSUE THREAD

**Issue by SaraManfredi** [GarrettLab-UF/LipidMatch#8]
Hello,

I'm running LipidMatch with my own data (positive) ddMS2, the folders: output, ddMS, Pos and PosByClass created are empty.
  
This is the error message at the end of the running code:
"Read 103055 items
Error in seq.default(16, nextSBlock - s_indicies[s] - 2, 2) : 
  wrong sign in 'by' argument
Called from: seq.default(16, nextSBlock - s_indicies[s] - 2, 2)"

Someone can help me?

Thank you in advance

**Comment by jeremykoelmel** [comment]
This is a common error were there are MS/MS scans with 1 or less fragments. 
If you remove these it should resolve your issue.
Re-convert your files in MSConvert using the following parameters:

In the subset option (new MSConvert), under "Number of data points" put 2 in the first box, and nothing in the second. The following should be displayed:
DefaultArrayLength | 2-

This will remove all MS/MS scans with 1 or less fragment which are causing the issue. 

Let me know if this works. If not provide MSConvert parameters, vendor, and an example .ms2 data. As well as any new error messages.

**Comment by SaraManfredi** [comment]
I've used the MSConvert that come with ProteoWizard  at this web site: (http://proteowizard.sourceforge.net/download.html) and used the following parameters:

peakPicking | vendor msLevel=2-2
threshold | absolute .0001 most-intense
defaultArrayLength | 2-

The software don't convert the files: it's keep processing, but never complete the conversion. 

Here an example of one of the files that i've use and converted previously (with only peakPicking and Threshold filters), the same that has caused the error:

[08-05-19_ddMS2_pos.zip](https://github.com/GarrettLab-UF/LipidMatch/files/3519320/08-05-19_ddMS2_pos.zip)

**Comment by jeremykoelmel** [comment]
Please report this MSConvert related issue to:
https://github.com/ProteoWizard/pwiz/issues

**Comment by jeremykoelmel** [comment]
Can you include solution here?

**Comment by SaraManfredi** [comment]
I've used the R and MSConverter version that come with LipidMatchflow
